#!/bin/sh
set -e

# work around eternal udev BLKRRPART ioctl hang with ntfs-3g
# (https://launchpad.net/bugs/1398859)
if [ -f /sys/fs/cgroup/cpu,cpuacct/tasks ]; then
    echo $$ > /sys/fs/cgroup/cpu,cpuacct/tasks
elif [ -e /sys/fs/cgroup/cgmanager/sock ]; then
    gdbus call -a unix:path=/sys/fs/cgroup/cgmanager/sock -o /org/linuxcontainers/cgmanager -m org.linuxcontainers.cgmanager0_0.MovePidAbs 'cpu,cpuacct' '/' $$
fi

# succeeding test must not write anything to stderr, as per DEP-8
mkdir -p /var/run/udisks2
src/tests/integration-test 2>&1
